print('------- Desafio 004 -------')
n = input('Digite algo: ')
print('Qual é o seu tipo primitivo? ', type(n))
print('{} é alfanumérico?'.format(n), n.isalnum())
print('{} é alfabético?'.format(n), n.isalpha())
print('{} é numérico?'.format(n), n.isnumeric())
print('{} é decimal?'.format(n), n.isdecimal())
print('{} está todo maiusculo?'.format(n), n.isupper())
print('{} é um espaço?'.format(n), n.isspace())
print('{} é um identificador?'.format(n), n.isidentifier())
print('{} é printável?'.format(n), n.isprintable())