nome = str(input('Digite o seu nome completo: '))
print(nome.upper())
print(nome.lower())
print(len(nome.replace(' ','')))
n = (nome.split())
print('Tem {} letras no primeiro nome.'.format(len(n[0])))
